/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INI = 3;
  /** RegularExpression Id. */
  int BODY = 4;
  /** RegularExpression Id. */
  int FBODY = 5;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinComment = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "\"/*\"",
    "<INI>",
    "\"<tbody>\"",
    "\"</tbody>\"",
  };

}
